### ISSUE TITLE
How to make a proguard with this lib ?

### ISSUE THREAD

**Issue by budioktaviyan** [zetbaitsu/Compressor#12]
I'm build the APK using proguard, and it says that I've to make some proguard config using your library. Could you explain me how to add a proguard config for your lib ?

**Comment by zetbaitsu** [comment]
Actually compressor have dependency to RxJava, so try to use RxJava proguard rules like this https://github.com/artem-zinnatullin/RxJavaProGuardRules/blob/master/rxjava-proguard-rules/proguard-rules.txt

**Comment by amiyo-biswas-mongia** [comment]
```
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}


-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}
```

Showing unresolved.
