### ISSUE TITLE
Video file size increased after compression

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [zetbaitsu/Compressor#135]
I tried to compress a 15 MB video file and after compression, the file size became 22 MB.
The following is the code i'm using:-
`String compressedVideoFilePath = SiliCompressor.with(context)                     
                                                   .compressVideo(actualVideoFile.getAbsolutePath(), actualFileDirPath);`
`File compressedVideoFile = new File(compressedVideoFilePath);`
`float fileSizeAfterCompress = (float) (compressedVideoFile.length() / (1024.0 * 1024.0));`

**Comment by zetbaitsu** [comment]
Sorry, I think you are in the wrong place. For `SiliCompressor` issue please post at this repo https://github.com/Tourenathan-G5organisation/SiliCompressor
