### ISSUE TITLE
Not able to call compress method in Java

### ISSUE THREAD

**Issue by DevKalpeshSathe** [zetbaitsu/Compressor#138]
Was trying to implement in java but giving errors.  If possible guide for implementation in Java.

Object f = Compressor.INSTANCE.compress(c, new File(finalDestination.getPath()), Dispatchers.getIO(), (Function1<Compression, Unit>) unit -> {
            return Unit.INSTANCE;
        }, new Continuation<File>() {
            @NotNull
            @Override
            public CoroutineContext getContext() {
                return Dispatchers.getIO();
            }

            @Override
            public void resumeWith(@NotNull Object o) {
                File file = (File) o;
            }
        });

**Comment by zetbaitsu** [comment]
For java, you can use older version https://github.com/zetbaitsu/Compressor/blob/master/README_v2.md or try implement using this solution https://github.com/zetbaitsu/Compressor/blob/master/README_v2.md
