### ISSUE TITLE
'Compressor()' has private access in 'id.zelore.compressor.Compressor

### ISSUE THREAD

**Issue by cradlesnatcher** [zetbaitsu/Compressor#146]
Bitmap thumb_bitmap = new Compressor(this)
                        .setMaxWidth(200)
                        .setMaxHeight(200)
                        .setQuality(75)
                        .compressToBitmap(thumb_filePath);

**Comment by Srt9930** [comment]
same here :<

**Comment by Srt9930** [comment]
solution : Try this implementation from the old library , Don't update it to 3.0.0
implementation 'id.zelory:compressor:2.1.0'
