### ISSUE TITLE
compress Bitmap to Bitmap

### ISSUE THREAD

**Issue by irsalshabirin** [zetbaitsu/Compressor#15]
I want to compress Bitmap to Bitmap, please help me ?
👍  👍

**Comment by charleston10** [comment]
You need get bitmap and save how to file, after this will convert file to bitmap

**Comment by af913337456** [comment]
you can use Bitmap.compress(...)

**Comment by irsalshabirin** [comment]
Thanks before, 😎

**Comment by tamilanmanikandan** [comment]
how to compress bitmap file
