### ISSUE TITLE
Migration from JCenter

### ISSUE THREAD

**Issue by jakoss** [zetbaitsu/Compressor#176]
In may this library won't be available from JCenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Please migrate this library to some other repository

**Comment by zetbaitsu** [comment]
Uploaded to maven central https://search.maven.org/artifact/id.zelory/compressor

**Comment by jakoss** [comment]
Thanks!

**Comment by jakoss** [comment]
@zetbaitsu i'm not sure if that's related, but i have strange error during gradle sync:
```
Failed to resolve: :unspecified:
Affected Modules: app
```

Removing the compressor dependency seems to fix that

**Comment by ivanpons** [comment]
There is a problem with the dependencies. There is a "unspecified" dependenciy

**Comment by jakoss** [comment]
@ivanpons nice timing, 30 seconds apart! :D

**Comment by daverix** [comment]
@ivanpons I have the same problem and created #179 before finding this issue.

**Comment by zetbaitsu** [comment]
@ivanpons and @klvnmacharia Please check this comment https://github.com/zetbaitsu/Compressor/issues/179#issuecomment-804110506

**Comment by klvnmacharia** [comment]
Thanks @zetbaitsu
