### ISSUE TITLE
observeOn(AndroidSchedulers.mainThread())方法报错，使用rxandroid2.x.y

### ISSUE THREAD

**Issue by Qvechar** [zetbaitsu/Compressor#43]
//压缩
//    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex:rxandroid:1.2.1'
//    compile 'io.reactivex.rxjava2:rxjava:2.0.1'

**Comment by zetbaitsu** [comment]
updated to RxJava 2
