### ISSUE TITLE
Upgrade to RxJava2.0.1

### ISSUE THREAD

**Issue by Xiasm** [zetbaitsu/Compressor#53]
my project use RxJava2.0.1, and i use this lib to handler image,.
Then when i run my project like this:
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/rxjava.properties
  	File1: /Users/envative/.gradle/caches/modules-2/files-2.1/io.reactivex/rxjava/1.1.6/2586312cd2b8a511e4c6236736f5a039fc0f2273/rxjava-1.1.6.jar
  	File2: /Users/envative/.gradle/caches/modules-2/files-2.1/io.reactivex.rxjava2/rxjava/2.0.1/57f850a6b317e5582f1dbaff10a9e7d7e1fcdcfb/rxjava-2.0.1.jar

**Comment by whenasmile** [comment]
+1

**Comment by whenasmile** [comment]
Now you can do this to advoid this problem.
exclude 'META-INF/rxjava.properties'

**Comment by sp-1234** [comment]
Also, if you already use rxjava, disable transitive dependencies for this lib.

**Comment by sp-1234** [comment]
this is duplicate btw https://github.com/zetbaitsu/Compressor/issues/50

**Comment by zetbaitsu** [comment]
updated to RxJava 2
