### ISSUE TITLE
 error: incompatible types: io.reactivex.Scheduler cannot be converted to rx.Scheduler

### ISSUE THREAD

**Issue by ruby-sharma6851** [zetbaitsu/Compressor#57]
i m Getting error in this line:
Compressor.getDefault(this).compressToFileAsObservable(actualImage) .subscribeOn(Schedulers.io()) .observeOn(AndroidSchedulers.mainThread())

i m using android studio 2.3.1
and my project using this lib.
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
                    .

**Comment by SagarAghara** [comment]
you solved your problem....???...Please help me if you solved....Thanks in Advance

**Comment by ebot64** [comment]
The MainActivity.java in the sample app still references the old id.zelory.compressor.Compressor.java file using rxjava1.x.x. It needs to reference the new import id.zelory.compressor.Compressor.java file containing rxjava2.x.x. I am still lost on how to change the reference myself

**Comment by ebot64** [comment]
I solved this error by commenting out the online source of the Compress library and uncommenting the library contained in the sample project. I replaced the following dependencies 
`dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'id.zelory:compressor:1.0.5'
    //compile project(':compressor')
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
}`
with this
`dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:25.3.1'
    //compile 'id.zelory:compressor:1.0.5'
    compile project(':compressor')
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
}`

Apparently the Compress.java file in the latest version 1.0.5 still uses rxjava1.x.x. Therefore, I am referencing the Compress.java file in the project. @zetbaitsu please update version 1.0.5 with rxjava 2.x.x implementation.

**Comment by zetbaitsu** [comment]
I have updated the rxjava with 2.1.0
