### ISSUE TITLE
why you use uri rather than File.getAbsolutePath() ??

### ISSUE THREAD

**Issue by 08carmelo** [zetbaitsu/Compressor#60]
public File compressToFile(File file) {
        return ImageUtil.compressImage(context, Uri.fromFile(file), maxWidth, maxHeight,
            compressFormat, bitmapConfig, quality, destinationDirectoryPath,
            fileNamePrefix, fileName);
    }

**Comment by sp-1234** [comment]
Uri can link to a File which would be inaccessible "directly".
Basically, learn Android before complaining.

**Comment by 08carmelo** [comment]
- garbage code.


2017-06-09 16:24 GMT+08:00 sp-1234 <notifications@github.com>:
