### ISSUE TITLE
Pointless comparison: bmp will be always null, by definition

### ISSUE THREAD

**Issue by sp-1234** [zetbaitsu/Compressor#62]
https://github.com/zetbaitsu/Compressor/blob/master/compressor/src/main/java/id/zelory/compressor/ImageUtil.java#L44

    options.inJustDecodeBounds = true;
    Bitmap bmp = BitmapFactory.decodeFile(filePath, options);
    if (bmp == null) {  // <- this is pointless
        …

Also, later in this method there are lots of more novice-tier errors (which I am too lazy to point out), so I doubt there is a point in doing a library with that quality of code. IMO one should learn Java and Android first…

**Comment by zetbaitsu** [comment]
thanks for the feedback, I have updated the code..
