### ISSUE TITLE
Image gets rotated

### ISSUE THREAD

**Issue by AniketBito** [zetbaitsu/Compressor#64]
Hi,
First, thanks for a great lib.
Second, I am getting an issue: Images are getting rotated 90% after compression. Could you please assist?

**Comment by sanderversluys** [comment]
Same issue here

**Comment by howard-e** [comment]
Same here, but only with pictures taken with the camera at the time of compression. Not for already stored images

**Comment by zerenato** [comment]
Same here. With pictures taken with the camera on portrait mode

**Comment by Ibernato93** [comment]
The image ctaken with the camera are always in portrait mode. You must rotate the image with the code.

**Comment by zetbaitsu** [comment]
Please try the latest version, 2.1.0

**Comment by botty87** [comment]
@zetbaitsu now it seems work fine! Also the path separator now is correct. Good work for me! ;)

**Comment by howard-e** [comment]
It's perfect now. Thanks @zetbaitsu. It's a great library and I'm happy with your good work!

**Comment by zerenato** [comment]
Worked for me too. Thanks @zetbaitsu :)

**Comment by joeferraro** [comment]
@zetbaitsu there seems to be a regression related to `2.1.0`. I'm now getting a null pointer on `android.graphics.Bitmap.getWidth()` for compressed pictures taken from the camera. Compressed pictures selected from the device do not throw this exception.

**Comment by ferminmoli** [comment]
Last version 0.16.0 which uses 2.1.0 compression version does not work. Please, fix it.
