### ISSUE TITLE
Which algorithm is being used in the library ?

### ISSUE THREAD

**Issue by m-a-y-a-n-k** [zetbaitsu/Compressor#65]
Can you please elaborate the compression algorithm used ? Some references would be a great help .

**Comment by zetbaitsu** [comment]
Actually I just wrap the method Bitmap.compress from android sdk, the actual implemetation of image compression is from android sdk and sorry I don't know which algorithm used. You can read here https://developer.android.com/reference/android/graphics/Bitmap.html#compress(android.graphics.Bitmap.CompressFormat, int, java.io.OutputStream)

**Comment by m-a-y-a-n-k** [comment]
Thanks , friend .
Your compression util is great. It's minimal. I compressed a 100 photos in approximately 1.5 seconds.
