### ISSUE TITLE
Compresor doesn't change file name ending after compression to different format

### ISSUE THREAD

**Issue by GediminasZukas** [zetbaitsu/Compressor#76]
I am using 2.1.0 version.

Let's say I want to  compress `JPEG ` image and save it as  a `PNG` after compression.

The problem is that newly created `PNG` file name persists the same with `.jpg ` ending after such compression.

To avoid this, I have to do something like this: 

`.compressToFileAsFlowable(file, file.getName().replace(".jpg", ".png"))`

which is not good in my opinion and such thing should be handled by library.

**Comment by Duna** [comment]
ok, but if compression is webp then filename remains jpeg or png. Is it ok?
in builder a methid is welcome: .changeExtensionTo("webp")

**Comment by maher640** [comment]
I have the same problem. compression type is webp by they're saved as their original type!

**Comment by zetbaitsu** [comment]
Fixed on v3.0.0
