### ISSUE TITLE
The <application> tag in `mainfest.xml in the library might be unnecessary

### ISSUE THREAD

**Issue by fan31415** [zetbaitsu/Compressor#8]
The code below in the libary's manifest.xml is unnecessary and make mistake

` <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true" >
    </application>`

When I build gradle, it will tell me the

`Attribute application@label value=(@string/application_name) from AndroidManifest.xml:30:9
is also present at {id.zelory:compressor} value=(@string/app_name)
Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:26:5 to override`

When I follow the direction I fix this error, however I think maybe removing the <application> tag from library is a better solution for others.

**Comment by zetbaitsu** [comment]
Thanks
